name: Go Test

on: push

jobs:
  build-and-test:
    name: Go Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.10
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go Build
        run: go build -v .

      - name: Go Test
        run: go test -v ./...

      # TODO replace with container workflow (test, build, deploy, large test, release)
      - name: Upload go binary artifact
        uses: actions/upload-artifact@v1
        with:
          name: web-cli-binary
          path: web-cli

      # copied form https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/codemanufaktur/web-cli:latest
            ghcr.io/codemanufaktur/web-cli:1.0.0-beta