name: Go Test

on: push

jobs:
  build-and-test:
    name: Go Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.10
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go Build
        run: go build -v .

      - name: Go Test
        run: go test -v ./...